# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modify.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import *
from 数据库课程设计.str import adminOp
from 数据库课程设计.ui import newlysuccess
from 数据库课程设计.ui import images_rc


class Ui_Dialog(QMainWindow):
    def __init__(self):
        super(Ui_Dialog, self).__init__()
        self.setupUi(self)

    def setupUi(self, Dialog):
        self.setWindowIcon(QIcon(':images/tubiao.png'))
        Dialog.setObjectName("MainWindow")
        Dialog.resize(800, 600)

        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(70, 30, 300, 50))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(70, 100, 72, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")


        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(120, 100, 200, 21))
        self.lineEdit.setObjectName("lineEdit")
        # 姓名

        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(120, 130, 200, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        # 年龄

        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(70, 130, 72, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.combobox = QtWidgets.QComboBox(Dialog)
        self.combobox.setGeometry(QtCore.QRect(120, 160, 200, 21))
        self.combobox.setObjectName("lineEdit_3")
        self.combobox.addItems(['男', '女'])
        # 性别

        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(70, 160, 72, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit_4 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_4.setGeometry(QtCore.QRect(120, 190, 200, 21))
        self.lineEdit_4.setObjectName("lineEdit_4")
        # 电话

        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(70, 190, 72, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(140, 230, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.addition)
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def addition(self):
        # id, name, age, sex, tele
        name = self.lineEdit.text()
        age = self.lineEdit_2.text()
        sex = self.combobox.currentText()
        tele = self.lineEdit_4.text()
        print(name)
        print(age)
        print(sex)
        print(tele)
        if adminOp.addStu(name, age, sex, tele):
            self.hide()
            self.f = newlysuccess.Ui_Dialog()
            self.f.show()
        else:
            QMessageBox.warning(self, '错误', '输入有误', QMessageBox.Yes | QMessageBox.No)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "建立信息"))
        self.label.setText(_translate("Dialog", "请输入学生的信息"))
        self.label_2.setText(_translate("Dialog", "姓名："))
        self.label_3.setText(_translate("Dialog", "年龄："))
        self.label_4.setText(_translate("Dialog", "性别："))
        self.label_5.setText(_translate("Dialog", "电话："))
        self.pushButton.setText(_translate("Dialog", "确定"))


if __name__ == '__main__':
    app = QApplication(sys.argv)
    w = Ui_Dialog()
    w.show()
    sys.exit(app.exec_())
