# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import *
from 数据库课程设计.ui import images_rc
from 数据库课程设计.str import adminOp
from 数据库课程设计.ui import addition
from 数据库课程设计.ui import Deletestudents
from 数据库课程设计.ui import exhibit
from 数据库课程设计.ui import revise
from 数据库课程设计.ui import additioncurriculum
from 数据库课程设计.ui import Deletecurriculum


class Ui_Dialog(QMainWindow):
    def __init__(self):
        super(Ui_Dialog, self).__init__()
        self.setupUi(self)

    def setupUi(self, Dialog):
        self.setWindowIcon(QIcon(':images/tubiao.png'))
        Dialog.setObjectName("MainWindow")
        Dialog.resize(800, 600)

        window_pale = QtGui.QPalette()
        window_pale.setBrush(self.backgroundRole(), QtGui.QBrush(QtGui.QPixmap(":images/beijing.jpg")))
        self.setPalette(window_pale)

        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(800, 550)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(60, 160, 72, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(180, 160, 72, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(290, 160, 72, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(40, 200, 710, 250))
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(50, 50, 100, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.addition)

        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(170, 50, 100, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.Deletestudents)

        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(290, 50, 100, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.revise)

        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(410, 50, 100, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(self.exhibit)

        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(530, 50, 100, 28))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.clicked.connect(self.additioncurriculum)

        self.pushButton_6 = QtWidgets.QPushButton(Dialog)
        self.pushButton_6.setGeometry(QtCore.QRect(650, 50, 100, 28))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_6.clicked.connect(self.Deletecurriculum)

        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(390, 160, 72, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(480, 160, 72, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(570, 160, 72, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(670, 160, 72, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.display()

    def Deletecurriculum(self):
        self.f = Deletecurriculum.Ui_Dialog()
        self.f.show()

    def additioncurriculum(self):
        self.f = additioncurriculum.Ui_Dialog()
        self.f.show()

    def revise(self):
        self.f = revise.Ui_Dialog()
        self.f.show()

    def exhibit(self):
        self.f = exhibit.Ui_Dialog()
        self.f.show()

    def Deletestudents(self):
        self.f = Deletestudents.Ui_Dialog()
        self.f.show()

    def addition(self):
        self.f = addition.Ui_Dialog()
        self.f.show()

    def display(self):
        data = adminOp.ShowAllSelection()
        self.textBrowser.setText('')
        for lis in data:
            print(lis)
            self.textBrowser.append(
                '  ' + str(lis['Sname']) + '\t       ' + str(lis['Sid']) + '          ' + lis[
                    'Ssex'] + '          ' + str(lis['Sage']) + '    ' + str(lis['Stele']) + '    ' + str(
                    lis['Jid']) + '        ' + str(lis['Jname']))

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "管理"))
        self.label_6.setText(_translate("Dialog", "姓名"))
        self.label_8.setText(_translate("Dialog", "学号"))
        self.label_9.setText(_translate("Dialog", "性别"))
        self.pushButton.setText(_translate("Dialog", "添加学生"))
        self.pushButton_2.setText(_translate("Dialog", "删除学生"))
        self.pushButton_3.setText(_translate("Dialog", "查询学生信息"))
        self.pushButton_4.setText(_translate("Dialog", "全部学生信息"))
        self.pushButton_5.setText(_translate("Dialog", "添加课程"))
        self.pushButton_6.setText(_translate("Dialog", "删除课程"))
        self.label_10.setText(_translate("Dialog", "年龄"))
        self.label_11.setText(_translate("Dialog", "电话"))
        self.label_12.setText(_translate("Dialog", "课程号"))
        self.label_13.setText(_translate("Dialog", "课程名"))


if __name__ == '__main__':
    app = QApplication(sys.argv)
    w = Ui_Dialog()
    w.show()
    sys.exit(app.exec_())
