# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'curriculum.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import *
from 数据库课程设计.str import studentsOp
from 数据库课程设计.ui import images_rc


class Ui_Dialog(QMainWindow):
    def __init__(self, Sid):
        self.Sid = Sid
        super(Ui_Dialog, self).__init__()
        self.setupUi(self)

    def setupUi(self, Dialog):
        self.setWindowIcon(QIcon(':images/tubiao.png'))
        Dialog.setObjectName("MainWindow")
        Dialog.resize(800, 600)

        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 80, 168, 23))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(200, 70, 111, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(150, 150, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.Course)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def Course(self):
        stuNumber = -1
        sign = -1
        stuNumber = self.lineEdit.text()
        print(stuNumber)
        print(self.Sid)
        if stuNumber != -1:
            sign = studentsOp.stuSele(self.Sid, int(stuNumber))

        if sign == -1:
            QMessageBox.warning(self, '错误', '无输入', QMessageBox.Yes | QMessageBox.No)
        elif sign == 0:
            print('0')
            QMessageBox.warning(self, '错误', '您已经选过该课程了', QMessageBox.Yes | QMessageBox.No)
        elif sign == 1:
            print('1')
            QMessageBox.warning(self, '错误', '您课程已满，不能进行选课', QMessageBox.Yes | QMessageBox.No)

        elif sign == 2:
            print('2')
            QMessageBox.warning(self, '正确', '选课成功', QMessageBox.Yes | QMessageBox.No)

        elif sign == 3:
            print('3')
            QMessageBox.warning(self, '错误', '您已经选过该课程了', QMessageBox.Yes | QMessageBox.No)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "选课界面"))
        self.label.setText(_translate("Dialog", "请输入课程号："))
        self.pushButton.setText(_translate("Dialog", "确定"))


if __name__ == '__main__':
    app = QApplication(sys.argv)
    w = Ui_Dialog(20003)
    w.show()
    sys.exit(app.exec_())
