# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'denlu.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from PyQt5.QtGui import QIcon, QPixmap
from PyQt5.QtWidgets import *
from 数据库课程设计.ui import user
from 数据库课程设计.ui import admin
from 数据库课程设计.str import adminOp
from 数据库课程设计.str import studentsOp
from 数据库课程设计.ui import images_rc


class Ui_Form(QMainWindow):
    def __init__(self):
        super(Ui_Form, self).__init__()
        self.setupUi(self)

    def setupUi(self, Form):
        self.setWindowIcon(QIcon(':images/tubiao.png'))
        Form.setObjectName("学生信息管理查询系统")
        Form.resize(400, 300)

        window_pale = QtGui.QPalette()
        pix = QtGui.QPixmap(":images/log.jpg")
        pix = pix.scaled(Form.width(), Form.height())
        window_pale.setBrush(self.backgroundRole(), QtGui.QBrush(pix))
        self.setPalette(window_pale)

        lb1 = QLabel(self)
        lb1.move(0, 70)
        lb1.setStyleSheet('backgroud-color:rad')

        map = QPixmap(':images/tubiao.png')
        lb1.setPixmap(map)
        lb1.resize(80, 80)
        lb1.setScaledContents(True)

        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(90, 70, 72, 15))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(90, 110, 72, 15))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(140, 70, 161, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(140, 110, 161, 21))
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setPlaceholderText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(140, 190, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.slot_btn_function)
        # self.pushButton.clicked.connect(self.onClick_Button)

        self.radioButton = QtWidgets.QRadioButton(Form)
        self.radioButton.setGeometry(QtCore.QRect(100, 150, 115, 19))
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")

        self.radioButton.clicked.connect(self.Transformation)

        self.radioButton_2 = QtWidgets.QRadioButton(Form)
        self.radioButton_2.setGeometry(QtCore.QRect(240, 150, 115, 19))
        self.radioButton_2.setChecked(False)
        self.radioButton_2.setObjectName("radioButton_2")

        self.radioButton_2.clicked.connect(self.Transformation)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def slot_btn_function(self):
        if self.radioButton.isChecked():
            user = int(self.lineEdit.text())
            psd = self.lineEdit_2.text()
            print(user, psd)
        else:
            name = self.lineEdit.text()
            id = int(self.lineEdit_2.text())
            print(name, id)

        if self.radioButton.isChecked():
            if adminOp.admLog(user, psd):
                self.admin()
            else:
                QMessageBox.warning(self, '错误', '账号或密码输入错误', QMessageBox.Yes | QMessageBox.No)
        else:
            if studentsOp.stuLog(name, id):
                self.user(id)
            # a = Login.Login(zhanghao, mima)
            # b = a.login()
            # # print(b)
            # if b:
            #     self.yonghu(name=b['name'], id=b['id'], sid=b['sid'], number=b['number'])
            else:
                QMessageBox.warning(self, '错误', '账号或密码输入错误', QMessageBox.Yes | QMessageBox.No)

    def admin(self):
        self.hide()
        self.f = admin.Ui_Dialog()
        self.f.show()

    def user(self, b):
        # print(b)
        # b = self.lineEdit.text()
        # print(type(b))
        self.hide()
        self.f = user.Ui_Dialog(b)
        self.f.show()

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "学生信息管理查询系统"))
        self.label.setText(_translate("Form", "账号："))
        self.label_2.setText(_translate("Form", "密码："))
        self.pushButton.setText(_translate("Form", "确定"))
        self.radioButton.setText(_translate("Form", "管理员"))
        self.radioButton_2.setText(_translate("Form", "学生"))

    def Transformation(self):
        if self.radioButton.isChecked():
            print('1')
            _translate = QtCore.QCoreApplication.translate
            self.label.setText(_translate("Form", "账号："))
            self.label_2.setText(_translate("Form", "密码："))

        else:
            print('2')
            _translate = QtCore.QCoreApplication.translate
            self.label.setText(_translate("Form", "姓名："))
            self.label_2.setText(_translate("Form", "学号："))


if __name__ == '__main__':
    app = QApplication(sys.argv)
    w = Ui_Form()
    w.show()
    sys.exit(app.exec_())
