# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import *
from 数据库课程设计.str import studentsOp
from 数据库课程设计.ui import Course, curriculum, modify
from 数据库课程设计.ui import images_rc


class Ui_Dialog(QMainWindow):
    def __init__(self, id):
        print(id)
        self.id = id
        super(Ui_Dialog, self).__init__()
        self.setupUi(self)

    def setupUi(self, Dialog):
        self.setWindowIcon(QIcon(':images/tubiao.png'))
        Dialog.setObjectName("MainWindow")
        Dialog.resize(800, 600)

        window_pale = QtGui.QPalette()
        window_pale.setBrush(self.backgroundRole(), QtGui.QBrush(QtGui.QPixmap(":images/beijing.jpg")))
        self.setPalette(window_pale)

        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(800, 550)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 50, 72, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(170, 50, 72, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(360, 50, 72, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(470, 50, 72, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(660, 50, 72, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(30, 100, 100, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(50, 160, 72, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(140, 160, 72, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(240, 160, 72, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")

        # print(data)
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(40, 200, 350, 250))
        self.textBrowser.setObjectName("textBrowser")
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.textBrowser.setFont(font)

        # 选课信息

        data = studentsOp.showStuInfor(self.id)
        self.textBrowser_2 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_2.setGeometry(QtCore.QRect(80, 50, 70, 28))
        self.textBrowser_2.setObjectName("textBrowser_2")
        # 姓名

        self.textBrowser_3 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_3.setGeometry(QtCore.QRect(220, 50, 100, 28))
        self.textBrowser_3.setObjectName("textBrowser_3")
        # 学号

        self.textBrowser_4 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_4.setGeometry(QtCore.QRect(410, 50, 40, 28))
        self.textBrowser_4.setObjectName("textBrowser_4")
        # 性别

        self.textBrowser_5 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_5.setGeometry(QtCore.QRect(520, 50, 120, 28))
        self.textBrowser_5.setObjectName("textBrowser_5")
        # 电话

        self.textBrowser_6 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_6.setGeometry(QtCore.QRect(710, 50, 30, 28))
        self.textBrowser_6.setObjectName("textBrowser_6")
        # 年龄

        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(520, 200, 150, 40))
        self.pushButton.setObjectName("pushButton")
        # print(type(data[0]['Sid']))
        self.pushButton.clicked.connect(lambda: self.curriculum(data[0]['Sid']))

        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(520, 260, 150, 40))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.Course)

        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(520, 330, 150, 40))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.modify)

        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(520, 400, 150, 40))
        self.pushButton_4.setObjectName("pushButton_4")

        self.pushButton_4.clicked.connect(self.display)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.display()

    def modify(self):
        self.f = modify.Ui_Dialog(self.id)
        self.f.show()

    def display(self):
        data = studentsOp.stuShowSele(self.id)
        self.textBrowser.setText('')
        for lis in data:
            print(lis)
            self.textBrowser.append(
                '    ' + str(lis['Jid']) + '\t      ' + str(lis['Jcredit']) + '              ' + lis['Jname'])
        data = studentsOp.showStuInfor(self.id)
        self.textBrowser_2.setText(data[0]['Sname'])  # 姓名
        self.textBrowser_3.setText(str(data[0]['Sid']))  # 学号
        self.textBrowser_4.setText(data[0]['Ssex'])  # 性别
        self.textBrowser_5.setText(data[0]['Stele'])  # 电话
        self.textBrowser_6.setText(str(data[0]['Sage']))  # 年龄

    def curriculum(self, sid):
        print('----------------')
        print(sid)
        self.f = curriculum.Ui_Dialog(sid)
        self.f.show()

    def Course(self):
        self.f = Course.Ui_Dialog()
        self.f.show()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "学生信息"))
        self.label.setText(_translate("Dialog", "姓名："))
        self.label_2.setText(_translate("Dialog", "学号："))
        self.label_3.setText(_translate("Dialog", "性别："))
        self.label_4.setText(_translate("Dialog", "电话："))
        self.label_5.setText(_translate("Dialog", "年龄："))
        self.label_7.setText(_translate("Dialog", "选课信息："))
        self.label_6.setText(_translate("Dialog", "课程号"))
        self.label_8.setText(_translate("Dialog", "课程学分"))
        self.label_9.setText(_translate("Dialog", "课程名"))
        self.pushButton.setText(_translate("Dialog", "添加课程"))
        self.pushButton_2.setText(_translate("Dialog", "查看选课表"))
        self.pushButton_3.setText(_translate("Dialog", "修改个人信息"))
        self.pushButton_4.setText(_translate("Dialog", "刷新"))


if __name__ == '__main__':
    app = QApplication(sys.argv)
    w = Ui_Dialog(20001)
    w.show()
    sys.exit(app.exec_())
